### ISSUE TITLE
Mono.Addins on net6

### ISSUE THREAD

**Issue by deanmaoataristocrat** [mono/mono-addins#205]
Hi all, does Mono.Addins work on net6 platform. It goes an error, and it worked fine ion older platform (net472), but not net6 platform.  Has anyone done it? It supports net standard 2.0, should support net6. Thanks

Got following errors: 
System.InvalidOperationException: Add-in engine not initialized.
   at Mono.Addins.AddinEngine.CheckInitialized()
   at Mono.Addins.AddinEngine.get_Registry()
   at Mono.Addins.AddinEngine.CheckHostAssembly(Assembly asm)
   at Mono.Addins.AddinEngine.ValidateAddinRoots()
   at Mono.Addins.AddinEngine.GetAddin(String id)
   at Mono.Addins.TreeNode.ResetCachedData()
   at Mono.Addins.TreeNode.ResetCachedData()
   at Mono.Addins.TreeNode.ResetCachedData()
   at Mono.Addins.ExtensionContext.ResetCachedData()
   at Mono.Addins.AddinEngine.ResetCachedData()
   at Mono.Addins.Database.AddinDatabase.ResetCachedData()
   at Mono.Addins.Database.AddinDatabase.Shutdown()
   at Mono.Addins.AddinRegistry.Dispose()
   at Mono.Addins.AddinEngine.Shutdown()
   at Mono.Addins.AddinManager.Shutdown()

**Comment by slluis** [comment]
Yes, it works on net6. You may be hitting a bug though.

**Comment by deanmaoataristocrat** [comment]
> Yes, it works on net6. You may be hitting a bug though.

Thanks for confirming. I will my findings if I managed to get it working. :)

**Comment by deanmaoataristocrat** [comment]
@slluis  I think there is a bug in the code for Shutdown:
![image](https://user-images.githubusercontent.com/105764536/207480242-b4b12af8-f33c-4f14-be06-76d320a14174.png)

The code in CheckInitialized will be throwing exception:
![image](https://user-images.githubusercontent.com/105764536/207480476-52697ad6-5bdf-4a26-99a1-ebbac9697737.png)

so ideally, we should do the check and clean up first, then set the initialized = false

**Comment by slluis** [comment]
Yes, this looks like a bug. I'll fix.

**Comment by deanmaoataristocrat** [comment]
thanks @slluis

**Comment by LalitAtAristocrat** [comment]
Hi @slluis, may I ask the tentative timeline for resolving this issue? It will help us plan our changes. Thanks!

**Comment by deanmaoataristocrat** [comment]
Hi, 

Any plan to release a new version for fixing this? Thanks,

Regards,

**Comment by slluis** [comment]
I'll try to do it this week.

**Comment by slluis** [comment]
Fixed by https://github.com/mono/mono-addins/pull/208.
